# Author: Paolo Fantinel
# Creation Date: 04/11/2022


# column_types:
cat_columns:
  - Gender
  - Education_Level
  - Marital_Status
  - Income_Category
  - Card_Category
    
quant_columns:
  - Customer_Age
  - Dependent_count
  - Months_on_book
  - Total_Relationship_Count
  - Months_Inactive_12_mon
  - Contacts_Count_12_mon 
  - Credit_Limit
  - Total_Revolving_Bal
  - Avg_Open_To_Buy
  - Total_Amt_Chng_Q4_Q1
  - Total_Trans_Amt
  - Total_Trans_Ct 
  - Total_Ct_Chng_Q4_Q1
  - Avg_Utilization_Ratio
  
# target column name
target:
  Churn

# plot dictionary for eda
plot_dict:
  Churn:
    _histogram
  Customer_Age: 
    _histogram
  Marital_Status: 
    _value_counts
  Total_Trans_Ct: 
    _distribution

# parameters grid for gridsearch
param_grid:
  n_estimators: 
    - 200
    - 500
  max_features: 
    - auto
    - sqrt
  max_depth: 
    - 4
    - 5
    - 100
  criterion:
    - gini
    - entropy

# test/train set split (test set will be this fraction of the total)
split:
  0.3

  
  